apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: hamkkebu
  labels:
    app: auth-service-backend
    service: auth-service
data:
  DB_URL: "jdbc:mysql://hamkkebu-dev-mysql.xxxxxxxxxxxx.ap-northeast-2.rds.amazonaws.com:3306/hamkkebu_auth?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8"
  KAFKA_BOOTSTRAP_SERVERS: "localhost:9092"
  KEYCLOAK_AUTH_SERVER_URL: "http://localhost:8180"
  KEYCLOAK_REALM: "hamkkebu"
