apiVersion: v1
kind: Service
metadata:
  name: auth-service-frontend
  labels:
    app: auth-service-frontend
    service: auth-service
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: auth-service-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
